INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('1', '1001', NULL, '1', '管理员管理', 'adminmanage', '1', 'Hui-iconfont-root', '1', '0');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('101', '1001', '1', '1', '管理员列表', 'admin/admin-list.html', '1', NULL, '1', '1');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('103', '1001', '101', '3', '管理员添加', 'admin/admin-add.html', '2', NULL, '1', '1');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('104', '1001', '101', '4', '管理员修改', 'admin/admin-edit.html', '2', NULL, '1', '1');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('105', '1001', '101', '5', '管理员删除', 'admin/admin-delete.html', '2', NULL, '1', '1');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('106', '1001', '101', '6', '修改密码', 'admin/admin-pass.html', '2', NULL, '1', '1');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('107', '1001', '101', '7', '禁用', 'admin/admin-forbid.html', '2', NULL, '1', '1');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('108', '1001', '101', '8', '启用', 'admin/admin-resume.html', '2', NULL, '1', '1');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('102', '1001', '1', '2', '权限管理', 'role/role-list.html', '1', NULL, '1', '1');

INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('2', '1001', NULL, '99', '系统配置', 'system', '1', 'Hui-iconfont-system', '1', '0');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('201', '1001', '2', '1', '系统日志', 'log/system-log.html', '1', NULL, '1', '1');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('202', '1001', '2', '2', '基础产品组', 'productgroup/pgroup-list.html', '1', NULL, '1', '1');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('203', '1001', '202', '3', '产品组添加', 'productgroup/pgroup-add.html', '2', NULL, '1', '1');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('204', '1001', '202', '4', '产品组删除', 'productgroup/pgroup-delete.html', '2', NULL, '1', '1');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('205', '1001', '202', '5', '产品添加', 'productgroup/pgroup-addproduct.html', '2', NULL, '1', '1');


INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('3', '1001', NULL, '2', '上游管理', 'provider', '1', 'Hui-iconfont-banzhu', '1', '0');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('301', '1001', '3', '1', '供应商', 'provider/provider-list.html', '1', NULL, '1', '1');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('302', '1001', '3', '2', '通道管理', 'pchannel/channel-list.html', '1', NULL, '1', '1');


INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('4', '1001', NULL, '3', '下游管理', 'customer', '1', 'Hui-iconfont-vip', '1', '0');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('401', '1001', '4', '1', '客户列表', 'customer/customer-list.html', '1', NULL, '1', '1');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('5', '1001', NULL, '5', '订单管理', 'order', '1', 'Hui-iconfont-quanbudingdan', '1', '0');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('501', '1001', '5', '1', '今日订单', 'ordermanage/order-today.html', '1', NULL, '1', '1');
INSERT INTO `account`.`sys_menu` (`menu_no`, `application_code`, `menu_parent_no`, `menu_order`, `menu_name`, `menu_url`, `menu_type`, `menu_icon`, `is_visible`, `is_leaf`) VALUES ('502', '1001', '5', '2', '历史订单', 'ordermanage/order-history.html', '1', NULL, '1', '1');
